/**
 * Compiles all registry JSON files into a single TypeScript module.
 *
 * Usage: npx tsx scripts/build-registry.ts [path-to-secid-repo]
 * Default: looks for ../SecID/registry/
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const secidRepo = process.argv[2] || resolve(__dirname, "../../SecID");
const registryDir = join(secidRepo, "registry");

interface RegistryFile {
  namespace: string;
  type: string;
  [key: string]: unknown;
}

// Recursively find all .json files, excluding _deferred/ and _template files
function findJsonFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith("_")) continue;
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...findJsonFiles(fullPath));
    } else if (entry.endsWith(".json")) {
      results.push(fullPath);
    }
  }
  return results;
}

const files = findJsonFiles(registryDir);
const registry: Record<string, Record<string, RegistryFile>> = {};
let count = 0;

for (const filePath of files) {
  const raw = readFileSync(filePath, "utf-8");
  let data: RegistryFile;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    console.error(`FAIL: ${filePath} — ${e}`);
    continue;
  }

  const { type, namespace } = data;
  if (!type || !namespace) {
    console.error(`SKIP: ${filePath} — missing type or namespace`);
    continue;
  }

  if (!registry[type]) registry[type] = {};
  if (registry[type][namespace]) {
    console.error(`WARN: duplicate ${type}/${namespace} — overwriting`);
  }
  registry[type][namespace] = data;
  count++;
}

// Generate the output module
const output = `// AUTO-GENERATED by scripts/build-registry.ts — DO NOT EDIT
// ${count} namespaces compiled from ${secidRepo}/registry/
// Generated: ${new Date().toISOString()}

import type { Registry } from "./types";

export const REGISTRY: Registry = ${JSON.stringify(registry, null, 2)} as unknown as Registry;
`;

const outPath = join(__dirname, "../src/registry.ts");
writeFileSync(outPath, output, "utf-8");

// Summary
const types = Object.keys(registry).sort();
console.log(`Compiled ${count} namespaces across ${types.length} types:`);
for (const t of types) {
  const ns = Object.keys(registry[t]);
  console.log(`  ${t}: ${ns.length} namespaces`);
}
console.log(`Written to: ${outPath}`);
