/**
 * Regenerates src/tlds.ts from IANA's authoritative root-zone TLD list.
 *
 * Usage: npx tsx scripts/update-tlds.ts
 *
 * The list gates which namespace misses are worth recording (src/demand.ts):
 * a miss whose "domain" ends in something that is not a delegated TLD cannot
 * be a real organisation, so it is not recorded. New TLDs are delegated
 * rarely; run this when one matters. A stale list fails safe — an unlisted TLD
 * only means that miss is not recorded, resolution itself is unaffected.
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const SOURCE = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt";

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`${SOURCE}: HTTP ${res.status}`);
const text = await res.text();

const lines = text.split("\n").map((l) => l.trim()).filter(Boolean);
const header = lines.find((l) => l.startsWith("#")) ?? "";
const tlds = lines.filter((l) => !l.startsWith("#")).map((l) => l.toLowerCase());
if (tlds.length < 1000) throw new Error(`Suspiciously short TLD list (${tlds.length}) — refusing to write`);

const out = `// AUTO-GENERATED by scripts/update-tlds.ts — DO NOT EDIT
// Source: ${SOURCE}
// ${header.replace(/^#\s*/, "")}
// ${tlds.length} TLDs (lowercase; IDN TLDs in their xn-- A-label form)

export const IANA_TLDS: ReadonlySet<string> = new Set(
  ${JSON.stringify(tlds.join(" "))}.split(" "),
);
`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "../src/tlds.ts");
writeFileSync(outPath, out, "utf-8");
console.log(`Wrote ${tlds.length} TLDs to ${outPath}`);
